sonar.projectKey=backend-belajar-lintas-ronald
sonar.projectName=Template Backend Go
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.exclusions=**/*_test.go,**/mock/**,**/vendor/**,**/docs/**,**/scripts/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/mock/**

sonar.go.coverage.reportPaths=cover.out

sonar.sourceEncoding=UTF-8
