{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ include "preview.namespace" . }}
  labels:
    {{- include "preview.labels" . | nindent 4 }}
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          command: ["redis-server", "--requirepass", "{{ .Values.redis.password }}", "--port", "{{ .Values.redis.port }}"]
          ports:
            - containerPort: {{ .Values.redis.port }}
          readinessProbe:
            exec:
              command: ["redis-cli", "-a", "{{ .Values.redis.password }}", "-p", "{{ .Values.redis.port }}", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
{{- end }}
