/**
 * JWT refresh-token paradigm. Backend returns access + refresh tokens
 * with explicit expiry. Hand-written; mirrors what was previously
 * generated by kubb from /v1/auth/* endpoints.
 *
 * Response shape uses lintas envelope:
 * { success, code, message, data: {...}, timestamp }
 */

export interface JwtSignInResponse {
  success: true;
  code: number;
  message: string;
  data: {
    access_token: string;
    refresh_token: string;
    access_token_expires_in_sec: number;
    refresh_token_expires_in_sec: number;
    issued_at: number;
    user: { id: string; name?: string; email?: string };
    permissions?: string[];
  };
  timestamp: string;
}

export interface JwtRefreshResponse {
  success: true;
  code: number;
  message: string;
  data: {
    access_token: string;
    access_token_expires_in_sec: number;
    issued_at: number;
  };
  timestamp: string;
}

/**
 * Persistent session shape (what is stored on disk: localStorage or cookie).
 * Includes the raw tokens needed for refresh.
 */
export interface JwtStoredSession {
  access_token: string;
  refresh_token: string;
  access_token_expires_in_sec: number;
  refresh_token_expires_in_sec: number;
  issued_at: number;
  user: { id: string; name?: string; email?: string };
  permissions: string[];
}
