/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateTodoRequest } from './types/CreateTodoRequest.ts';
import type { ErrorResponse } from './types/ErrorResponse.ts';
import type { SuccessResponse } from './types/SuccessResponse.ts';
import type { TodoResponse } from './types/TodoResponse.ts';

/**
 * @description Created
 */
export type CreateTodo201 = SuccessResponse & {
  /**
   * @type object | undefined
   */
  data?: TodoResponse;
};

/**
 * @description Error response
 */
export type CreateTodo401 = ErrorResponse;

/**
 * @description Error response
 */
export type CreateTodo422 = ErrorResponse;

export type CreateTodoMutationRequest = CreateTodoRequest;

export type CreateTodoMutationResponse = CreateTodo201;

export type CreateTodoMutation = {
  Response: CreateTodo201;
  Request: CreateTodoMutationRequest;
  Errors: CreateTodo401 | CreateTodo422;
};
