/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';
import { createTodoRequestSchema } from './zod/createTodoRequestSchema.ts';
import { errorResponseSchema } from './zod/errorResponseSchema.ts';
import { successResponseSchema } from './zod/successResponseSchema.ts';
import { todoResponseSchema } from './zod/todoResponseSchema.ts';

/**
 * @description Created
 */
export const createTodo201Schema = z
  .lazy(() => successResponseSchema)
  .and(
    z.object({
      data: z.optional(z.lazy(() => todoResponseSchema))
    })
  );

/**
 * @description Error response
 */
export const createTodo401Schema = z.lazy(() => errorResponseSchema);

/**
 * @description Error response
 */
export const createTodo422Schema = z.lazy(() => errorResponseSchema);

export const createTodoMutationRequestSchema = z.lazy(() => createTodoRequestSchema);

export const createTodoMutationResponseSchema = z.lazy(() => createTodo201Schema);
