/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';
import { errorResponseSchema } from './zod/errorResponseSchema.ts';
import { successResponseSchema } from './zod/successResponseSchema.ts';

export const deleteTodoPathParamsSchema = z.object({
  id: z.string().uuid()
});

/**
 * @description Deleted
 */
export const deleteTodo200Schema = z.lazy(() => successResponseSchema);

/**
 * @description Error response
 */
export const deleteTodo401Schema = z.lazy(() => errorResponseSchema);

/**
 * @description Error response
 */
export const deleteTodo404Schema = z.lazy(() => errorResponseSchema);

export const deleteTodoMutationResponseSchema = z.lazy(() => deleteTodo200Schema);
