/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from './types/ErrorResponse.ts';
import type { SuccessResponse } from './types/SuccessResponse.ts';

export type DeleteTodoPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Deleted
 */
export type DeleteTodo200 = SuccessResponse;

/**
 * @description Error response
 */
export type DeleteTodo401 = ErrorResponse;

/**
 * @description Error response
 */
export type DeleteTodo404 = ErrorResponse;

export type DeleteTodoMutationResponse = DeleteTodo200;

export type DeleteTodoMutation = {
  Response: DeleteTodo200;
  PathParams: DeleteTodoPathParams;
  Errors: DeleteTodo401 | DeleteTodo404;
};
