/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Service is up.
 */
export type GetHealthz200 = {
  /**
   * @type string | undefined
   */
  status?: string;
};

export type GetHealthzQueryResponse = GetHealthz200;

export type GetHealthzQuery = {
  Response: GetHealthz200;
  Errors: any;
};
