/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

/**
 * @description Service is up.
 */
export const getHealthz200Schema = z.object({
  status: z.optional(z.string())
});

export const getHealthzQueryResponseSchema = z.lazy(() => getHealthz200Schema);
