/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from './types/ErrorResponse.ts';
import type { SuccessResponse } from './types/SuccessResponse.ts';
import type { TodoResponse } from './types/TodoResponse.ts';

export type GetTodoPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description OK
 */
export type GetTodo200 = SuccessResponse & {
  /**
   * @type object | undefined
   */
  data?: TodoResponse;
};

/**
 * @description Error response
 */
export type GetTodo401 = ErrorResponse;

/**
 * @description Error response
 */
export type GetTodo404 = ErrorResponse;

export type GetTodoQueryResponse = GetTodo200;

export type GetTodoQuery = {
  Response: GetTodo200;
  PathParams: GetTodoPathParams;
  Errors: GetTodo401 | GetTodo404;
};
