/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';
import { errorResponseSchema } from './zod/errorResponseSchema.ts';
import { successResponseSchema } from './zod/successResponseSchema.ts';
import { todoResponseSchema } from './zod/todoResponseSchema.ts';

export const getTodoPathParamsSchema = z.object({
  id: z.string().uuid()
});

/**
 * @description OK
 */
export const getTodo200Schema = z
  .lazy(() => successResponseSchema)
  .and(
    z.object({
      data: z.optional(z.lazy(() => todoResponseSchema))
    })
  );

/**
 * @description Error response
 */
export const getTodo401Schema = z.lazy(() => errorResponseSchema);

/**
 * @description Error response
 */
export const getTodo404Schema = z.lazy(() => errorResponseSchema);

export const getTodoQueryResponseSchema = z.lazy(() => getTodo200Schema);
