/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from './types/ErrorResponse.ts';
import type { PaginatedResponse } from './types/PaginatedResponse.ts';
import type { TodoResponse } from './types/TodoResponse.ts';

export type ListTodosQueryParams = {
  /**
   * @minLength 1
   * @default 1
   * @type integer | undefined
   */
  page?: number;
  /**
   * @minLength 1
   * @maxLength 100
   * @default 10
   * @type integer | undefined
   */
  page_size?: number;
};

/**
 * @description Paged list
 */
export type ListTodos200 = PaginatedResponse & {
  /**
   * @type array | undefined
   */
  data?: TodoResponse[];
};

/**
 * @description Error response
 */
export type ListTodos401 = ErrorResponse;

export type ListTodosQueryResponse = ListTodos200;

export type ListTodosQuery = {
  Response: ListTodos200;
  QueryParams: ListTodosQueryParams;
  Errors: ListTodos401;
};
