/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';
import { errorResponseSchema } from './zod/errorResponseSchema.ts';
import { paginatedResponseSchema } from './zod/paginatedResponseSchema.ts';
import { todoResponseSchema } from './zod/todoResponseSchema.ts';

export const listTodosQueryParamsSchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  page_size: z.coerce.number().int().min(1).max(100).default(10)
});

/**
 * @description Paged list
 */
export const listTodos200Schema = z
  .lazy(() => paginatedResponseSchema)
  .and(
    z.object({
      data: z.optional(z.array(z.lazy(() => todoResponseSchema)))
    })
  );

/**
 * @description Error response
 */
export const listTodos401Schema = z.lazy(() => errorResponseSchema);

export const listTodosQueryResponseSchema = z.lazy(() => listTodos200Schema);
