/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';
import { errorResponseSchema } from './zod/errorResponseSchema.ts';
import { logoutRequestSchema } from './zod/logoutRequestSchema.ts';
import { successResponseSchema } from './zod/successResponseSchema.ts';

/**
 * @description Logged out
 */
export const postAuthLogout200Schema = z.lazy(() => successResponseSchema);

/**
 * @description Error response
 */
export const postAuthLogout401Schema = z.lazy(() => errorResponseSchema);

export const postAuthLogoutMutationRequestSchema = z.lazy(() => logoutRequestSchema);

export const postAuthLogoutMutationResponseSchema = z.lazy(() => postAuthLogout200Schema);
