/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from './types/ErrorResponse.ts';
import type { RenewRequest } from './types/RenewRequest.ts';
import type { RenewResponse } from './types/RenewResponse.ts';
import type { SuccessResponse } from './types/SuccessResponse.ts';

/**
 * @description Renewed
 */
export type PostAuthRenew200 = SuccessResponse & {
  /**
   * @type object | undefined
   */
  data?: RenewResponse;
};

/**
 * @description Error response
 */
export type PostAuthRenew401 = ErrorResponse;

export type PostAuthRenewMutationRequest = RenewRequest;

export type PostAuthRenewMutationResponse = PostAuthRenew200;

export type PostAuthRenewMutation = {
  Response: PostAuthRenew200;
  Request: PostAuthRenewMutationRequest;
  Errors: PostAuthRenew401;
};
