/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';
import { errorResponseSchema } from './zod/errorResponseSchema.ts';
import { loginRequestSchema } from './zod/loginRequestSchema.ts';
import { loginResponseSchema } from './zod/loginResponseSchema.ts';
import { successResponseSchema } from './zod/successResponseSchema.ts';

/**
 * @description Logged in
 */
export const postAuthLogin201Schema = z
  .lazy(() => successResponseSchema)
  .and(
    z.object({
      data: z.optional(z.lazy(() => loginResponseSchema))
    })
  );

/**
 * @description Error response
 */
export const postAuthLogin401Schema = z.lazy(() => errorResponseSchema);

/**
 * @description Error response
 */
export const postAuthLogin422Schema = z.lazy(() => errorResponseSchema);

export const postAuthLoginMutationRequestSchema = z.lazy(() => loginRequestSchema);

export const postAuthLoginMutationResponseSchema = z.lazy(() => postAuthLogin201Schema);
