/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from './types/ErrorResponse.ts';
import type { LogoutRequest } from './types/LogoutRequest.ts';
import type { SuccessResponse } from './types/SuccessResponse.ts';

/**
 * @description Logged out
 */
export type PostAuthLogout200 = SuccessResponse;

/**
 * @description Error response
 */
export type PostAuthLogout401 = ErrorResponse;

export type PostAuthLogoutMutationRequest = LogoutRequest;

export type PostAuthLogoutMutationResponse = PostAuthLogout200;

export type PostAuthLogoutMutation = {
  Response: PostAuthLogout200;
  Request: PostAuthLogoutMutationRequest;
  Errors: PostAuthLogout401;
};
