/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';
import { errorResponseSchema } from './zod/errorResponseSchema.ts';
import { renewRequestSchema } from './zod/renewRequestSchema.ts';
import { renewResponseSchema } from './zod/renewResponseSchema.ts';
import { successResponseSchema } from './zod/successResponseSchema.ts';

/**
 * @description Renewed
 */
export const postAuthRenew200Schema = z
  .lazy(() => successResponseSchema)
  .and(
    z.object({
      data: z.optional(z.lazy(() => renewResponseSchema))
    })
  );

/**
 * @description Error response
 */
export const postAuthRenew401Schema = z.lazy(() => errorResponseSchema);

export const postAuthRenewMutationRequestSchema = z.lazy(() => renewRequestSchema);

export const postAuthRenewMutationResponseSchema = z.lazy(() => postAuthRenew200Schema);
