/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from './types/ErrorResponse.ts';
import type { LoginRequest } from './types/LoginRequest.ts';
import type { LoginResponse } from './types/LoginResponse.ts';
import type { SuccessResponse } from './types/SuccessResponse.ts';

/**
 * @description Logged in
 */
export type PostAuthLogin201 = SuccessResponse & {
  /**
   * @type object | undefined
   */
  data?: LoginResponse;
};

/**
 * @description Error response
 */
export type PostAuthLogin401 = ErrorResponse;

/**
 * @description Error response
 */
export type PostAuthLogin422 = ErrorResponse;

export type PostAuthLoginMutationRequest = LoginRequest;

export type PostAuthLoginMutationResponse = PostAuthLogin201;

export type PostAuthLoginMutation = {
  Response: PostAuthLogin201;
  Request: PostAuthLoginMutationRequest;
  Errors: PostAuthLogin401 | PostAuthLogin422;
};
