/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from './types/ErrorResponse.ts';
import type { SuccessResponse } from './types/SuccessResponse.ts';
import type { TodoResponse } from './types/TodoResponse.ts';
import type { UpdateTodoRequest } from './types/UpdateTodoRequest.ts';

export type UpdateTodoPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Updated
 */
export type UpdateTodo200 = SuccessResponse & {
  /**
   * @type object | undefined
   */
  data?: TodoResponse;
};

/**
 * @description Error response
 */
export type UpdateTodo401 = ErrorResponse;

/**
 * @description Error response
 */
export type UpdateTodo404 = ErrorResponse;

/**
 * @description Error response
 */
export type UpdateTodo422 = ErrorResponse;

export type UpdateTodoMutationRequest = UpdateTodoRequest;

export type UpdateTodoMutationResponse = UpdateTodo200;

export type UpdateTodoMutation = {
  Response: UpdateTodo200;
  Request: UpdateTodoMutationRequest;
  PathParams: UpdateTodoPathParams;
  Errors: UpdateTodo401 | UpdateTodo404 | UpdateTodo422;
};
