/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';
import { errorResponseSchema } from './zod/errorResponseSchema.ts';
import { successResponseSchema } from './zod/successResponseSchema.ts';
import { todoResponseSchema } from './zod/todoResponseSchema.ts';
import { updateTodoRequestSchema } from './zod/updateTodoRequestSchema.ts';

export const updateTodoPathParamsSchema = z.object({
  id: z.string().uuid()
});

/**
 * @description Updated
 */
export const updateTodo200Schema = z
  .lazy(() => successResponseSchema)
  .and(
    z.object({
      data: z.optional(z.lazy(() => todoResponseSchema))
    })
  );

/**
 * @description Error response
 */
export const updateTodo401Schema = z.lazy(() => errorResponseSchema);

/**
 * @description Error response
 */
export const updateTodo404Schema = z.lazy(() => errorResponseSchema);

/**
 * @description Error response
 */
export const updateTodo422Schema = z.lazy(() => errorResponseSchema);

export const updateTodoMutationRequestSchema = z.lazy(() => updateTodoRequestSchema);

export const updateTodoMutationResponseSchema = z.lazy(() => updateTodo200Schema);
