/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import fetch from '@/services/fetcher';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/services/fetcher';
import type {
  CreateTodoMutationRequest,
  CreateTodoMutationResponse,
  CreateTodo401,
  CreateTodo422
} from './CreateTodo.ts';

export const createTodoMutationKey = () => [{ url: '/v1/todos' }] as const;

export type CreateTodoMutationKey = ReturnType<typeof createTodoMutationKey>;

/**
 * @summary Create a todo
 * {@link /v1/todos}
 */
export async function createTodo(
  data: CreateTodoMutationRequest,
  config: Partial<RequestConfig<CreateTodoMutationRequest>> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateTodoMutationResponse,
    ResponseErrorConfig<CreateTodo401 | CreateTodo422>,
    CreateTodoMutationRequest
  >({ method: 'POST', url: `/v1/todos`, data: requestData, ...requestConfig });
  return res.data;
}

export function createTodoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<CreateTodoMutationRequest>> & { client?: Client } = {}
) {
  const mutationKey = createTodoMutationKey();
  return mutationOptions<
    CreateTodoMutationResponse,
    ResponseErrorConfig<CreateTodo401 | CreateTodo422>,
    { data: CreateTodoMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return createTodo(data, config);
    }
  });
}

/**
 * @summary Create a todo
 * {@link /v1/todos}
 */
export function useCreateTodo<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateTodoMutationResponse,
      ResponseErrorConfig<CreateTodo401 | CreateTodo422>,
      { data: CreateTodoMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateTodoMutationRequest>> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createTodoMutationKey();

  const baseOptions = createTodoMutationOptions(config) as UseMutationOptions<
    CreateTodoMutationResponse,
    ResponseErrorConfig<CreateTodo401 | CreateTodo422>,
    { data: CreateTodoMutationRequest },
    TContext
  >;

  return useMutation<
    CreateTodoMutationResponse,
    ResponseErrorConfig<CreateTodo401 | CreateTodo422>,
    { data: CreateTodoMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    CreateTodoMutationResponse,
    ResponseErrorConfig<CreateTodo401 | CreateTodo422>,
    { data: CreateTodoMutationRequest },
    TContext
  >;
}
