/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import fetch from '@/services/fetcher';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/services/fetcher';
import type {
  DeleteTodoMutationResponse,
  DeleteTodoPathParams,
  DeleteTodo401,
  DeleteTodo404
} from './DeleteTodo.ts';

export const deleteTodoMutationKey = () => [{ url: '/v1/todos/:id' }] as const;

export type DeleteTodoMutationKey = ReturnType<typeof deleteTodoMutationKey>;

/**
 * @summary Delete todo
 * {@link /v1/todos/:id}
 */
export async function deleteTodo(
  id: DeleteTodoPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteTodoMutationResponse,
    ResponseErrorConfig<DeleteTodo401 | DeleteTodo404>,
    unknown
  >({ method: 'DELETE', url: `/v1/todos/${id}`, ...requestConfig });
  return res.data;
}

export function deleteTodoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = deleteTodoMutationKey();
  return mutationOptions<
    DeleteTodoMutationResponse,
    ResponseErrorConfig<DeleteTodo401 | DeleteTodo404>,
    { id: DeleteTodoPathParams['id'] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteTodo(id, config);
    }
  });
}

/**
 * @summary Delete todo
 * {@link /v1/todos/:id}
 */
export function useDeleteTodo<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteTodoMutationResponse,
      ResponseErrorConfig<DeleteTodo401 | DeleteTodo404>,
      { id: DeleteTodoPathParams['id'] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteTodoMutationKey();

  const baseOptions = deleteTodoMutationOptions(config) as UseMutationOptions<
    DeleteTodoMutationResponse,
    ResponseErrorConfig<DeleteTodo401 | DeleteTodo404>,
    { id: DeleteTodoPathParams['id'] },
    TContext
  >;

  return useMutation<
    DeleteTodoMutationResponse,
    ResponseErrorConfig<DeleteTodo401 | DeleteTodo404>,
    { id: DeleteTodoPathParams['id'] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    DeleteTodoMutationResponse,
    ResponseErrorConfig<DeleteTodo401 | DeleteTodo404>,
    { id: DeleteTodoPathParams['id'] },
    TContext
  >;
}
