/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import fetch from '@/services/fetcher';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/services/fetcher';
import type { GetHealthzQueryResponse } from './GetHealthz.ts';

export const getHealthzSuspenseQueryKey = () => ['/healthz'] as const;

export type GetHealthzSuspenseQueryKey = ReturnType<typeof getHealthzSuspenseQueryKey>;

/**
 * @summary Liveness probe
 * {@link /healthz}
 */
export async function getHealthzSuspense(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<GetHealthzQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/healthz`,
    ...requestConfig
  });
  return res.data;
}

export function getHealthzSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getHealthzSuspenseQueryKey();
  return queryOptions<
    GetHealthzQueryResponse,
    ResponseErrorConfig<Error>,
    GetHealthzQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return getHealthzSuspense(config);
    }
  });
}

/**
 * @summary Liveness probe
 * {@link /healthz}
 */
export function useGetHealthzSuspense<
  TData = GetHealthzQueryResponse,
  TQueryKey extends QueryKey = GetHealthzSuspenseQueryKey
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<GetHealthzQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getHealthzSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getHealthzSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
