/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import fetch from '@/services/fetcher';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/services/fetcher';
import type { GetTodoQueryResponse, GetTodoPathParams, GetTodo401, GetTodo404 } from './GetTodo.ts';

export const getTodoSuspenseQueryKey = (id: GetTodoPathParams['id']) =>
  ['/v1/todos/:id', ...(id ? [id] : [])] as const;

export type GetTodoSuspenseQueryKey = ReturnType<typeof getTodoSuspenseQueryKey>;

/**
 * @summary Get todo by id
 * {@link /v1/todos/:id}
 */
export async function getTodoSuspense(
  id: GetTodoPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTodoQueryResponse,
    ResponseErrorConfig<GetTodo401 | GetTodo404>,
    unknown
  >({ method: 'GET', url: `/v1/todos/${id}`, ...requestConfig });
  return res.data;
}

export function getTodoSuspenseQueryOptions(
  id: GetTodoPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getTodoSuspenseQueryKey(id);
  return queryOptions<
    GetTodoQueryResponse,
    ResponseErrorConfig<GetTodo401 | GetTodo404>,
    GetTodoQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return getTodoSuspense(id, config);
    }
  });
}

/**
 * @summary Get todo by id
 * {@link /v1/todos/:id}
 */
export function useGetTodoSuspense<
  TData = GetTodoQueryResponse,
  TQueryKey extends QueryKey = GetTodoSuspenseQueryKey
>(
  id: GetTodoPathParams['id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetTodoQueryResponse,
        ResponseErrorConfig<GetTodo401 | GetTodo404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getTodoSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getTodoSuspenseQueryOptions(id, config),
      queryKey,
      ...queryOptions
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetTodo401 | GetTodo404>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
