/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';
import fetch from '@/services/fetcher';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/services/fetcher';
import type { GetHealthzQueryResponse } from './GetHealthz.ts';

export const getHealthzQueryKey = () => ['/healthz'] as const;

export type GetHealthzQueryKey = ReturnType<typeof getHealthzQueryKey>;

/**
 * @summary Liveness probe
 * {@link /healthz}
 */
export async function getHealthz(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<GetHealthzQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/healthz`,
    ...requestConfig
  });
  return res.data;
}

export function getHealthzQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const queryKey = getHealthzQueryKey();
  return queryOptions<
    GetHealthzQueryResponse,
    ResponseErrorConfig<Error>,
    GetHealthzQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return getHealthz(config);
    }
  });
}

/**
 * @summary Liveness probe
 * {@link /healthz}
 */
export function useGetHealthz<
  TData = GetHealthzQueryResponse,
  TQueryData = GetHealthzQueryResponse,
  TQueryKey extends QueryKey = GetHealthzQueryKey
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetHealthzQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getHealthzQueryKey();

  const query = useQuery(
    {
      ...getHealthzQueryOptions(config),
      queryKey,
      ...queryOptions
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
