/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult
} from '@tanstack/react-query';
import { queryOptions, useQuery } from '@tanstack/react-query';
import fetch from '@/services/fetcher';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/services/fetcher';
import type { ListTodosQueryResponse, ListTodosQueryParams, ListTodos401 } from './ListTodos.ts';

export const listTodosQueryKey = (params: ListTodosQueryParams = {}) =>
  ['/v1/todos', ...(params ? [params] : [])] as const;

export type ListTodosQueryKey = ReturnType<typeof listTodosQueryKey>;

/**
 * @summary List todos owned by the authenticated user
 * {@link /v1/todos}
 */
export async function listTodos(
  params?: ListTodosQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<ListTodosQueryResponse, ResponseErrorConfig<ListTodos401>, unknown>({
    method: 'GET',
    url: `/v1/todos`,
    params,
    ...requestConfig
  });
  return res.data;
}

export function listTodosQueryOptions(
  params?: ListTodosQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listTodosQueryKey(params);
  return queryOptions<
    ListTodosQueryResponse,
    ResponseErrorConfig<ListTodos401>,
    ListTodosQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return listTodos(params, config);
    }
  });
}

/**
 * @summary List todos owned by the authenticated user
 * {@link /v1/todos}
 */
export function useListTodos<
  TData = ListTodosQueryResponse,
  TQueryData = ListTodosQueryResponse,
  TQueryKey extends QueryKey = ListTodosQueryKey
>(
  params?: ListTodosQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListTodosQueryResponse,
        ResponseErrorConfig<ListTodos401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? listTodosQueryKey(params);

  const query = useQuery(
    {
      ...listTodosQueryOptions(params, config),
      queryKey,
      ...queryOptions
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ListTodos401>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
