/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query';
import fetch from '@/services/fetcher';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/services/fetcher';
import type { ListTodosQueryResponse, ListTodosQueryParams, ListTodos401 } from './ListTodos.ts';

export const listTodosSuspenseQueryKey = (params: ListTodosQueryParams = {}) =>
  ['/v1/todos', ...(params ? [params] : [])] as const;

export type ListTodosSuspenseQueryKey = ReturnType<typeof listTodosSuspenseQueryKey>;

/**
 * @summary List todos owned by the authenticated user
 * {@link /v1/todos}
 */
export async function listTodosSuspense(
  params?: ListTodosQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<ListTodosQueryResponse, ResponseErrorConfig<ListTodos401>, unknown>({
    method: 'GET',
    url: `/v1/todos`,
    params,
    ...requestConfig
  });
  return res.data;
}

export function listTodosSuspenseQueryOptions(
  params?: ListTodosQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listTodosSuspenseQueryKey(params);
  return queryOptions<
    ListTodosQueryResponse,
    ResponseErrorConfig<ListTodos401>,
    ListTodosQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return listTodosSuspense(params, config);
    }
  });
}

/**
 * @summary List todos owned by the authenticated user
 * {@link /v1/todos}
 */
export function useListTodosSuspense<
  TData = ListTodosQueryResponse,
  TQueryKey extends QueryKey = ListTodosSuspenseQueryKey
>(
  params?: ListTodosQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListTodosQueryResponse,
        ResponseErrorConfig<ListTodos401>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? listTodosSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...listTodosSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListTodos401>> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
