/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import fetch from '@/services/fetcher';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/services/fetcher';
import type {
  PostAuthRenewMutationRequest,
  PostAuthRenewMutationResponse,
  PostAuthRenew401
} from './PostAuthRenew.ts';

export const postAuthRenewMutationKey = () => [{ url: '/v1/auth/renew' }] as const;

export type PostAuthRenewMutationKey = ReturnType<typeof postAuthRenewMutationKey>;

/**
 * @summary Renew access token using refresh token
 * {@link /v1/auth/renew}
 */
export async function postAuthRenew(
  data: PostAuthRenewMutationRequest,
  config: Partial<RequestConfig<PostAuthRenewMutationRequest>> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAuthRenewMutationResponse,
    ResponseErrorConfig<PostAuthRenew401>,
    PostAuthRenewMutationRequest
  >({ method: 'POST', url: `/v1/auth/renew`, data: requestData, ...requestConfig });
  return res.data;
}

export function postAuthRenewMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostAuthRenewMutationRequest>> & { client?: Client } = {}
) {
  const mutationKey = postAuthRenewMutationKey();
  return mutationOptions<
    PostAuthRenewMutationResponse,
    ResponseErrorConfig<PostAuthRenew401>,
    { data: PostAuthRenewMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postAuthRenew(data, config);
    }
  });
}

/**
 * @summary Renew access token using refresh token
 * {@link /v1/auth/renew}
 */
export function usePostAuthRenew<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAuthRenewMutationResponse,
      ResponseErrorConfig<PostAuthRenew401>,
      { data: PostAuthRenewMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostAuthRenewMutationRequest>> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postAuthRenewMutationKey();

  const baseOptions = postAuthRenewMutationOptions(config) as UseMutationOptions<
    PostAuthRenewMutationResponse,
    ResponseErrorConfig<PostAuthRenew401>,
    { data: PostAuthRenewMutationRequest },
    TContext
  >;

  return useMutation<
    PostAuthRenewMutationResponse,
    ResponseErrorConfig<PostAuthRenew401>,
    { data: PostAuthRenewMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostAuthRenewMutationResponse,
    ResponseErrorConfig<PostAuthRenew401>,
    { data: PostAuthRenewMutationRequest },
    TContext
  >;
}
