/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import fetch from '@/services/fetcher';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/services/fetcher';
import type {
  PostAuthLoginMutationRequest,
  PostAuthLoginMutationResponse,
  PostAuthLogin401,
  PostAuthLogin422
} from './PostAuthLogin.ts';

export const postAuthLoginMutationKey = () => [{ url: '/v1/auth/login' }] as const;

export type PostAuthLoginMutationKey = ReturnType<typeof postAuthLoginMutationKey>;

/**
 * @summary Sign in with email + password
 * {@link /v1/auth/login}
 */
export async function postAuthLogin(
  data: PostAuthLoginMutationRequest,
  config: Partial<RequestConfig<PostAuthLoginMutationRequest>> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAuthLoginMutationResponse,
    ResponseErrorConfig<PostAuthLogin401 | PostAuthLogin422>,
    PostAuthLoginMutationRequest
  >({ method: 'POST', url: `/v1/auth/login`, data: requestData, ...requestConfig });
  return res.data;
}

export function postAuthLoginMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostAuthLoginMutationRequest>> & { client?: Client } = {}
) {
  const mutationKey = postAuthLoginMutationKey();
  return mutationOptions<
    PostAuthLoginMutationResponse,
    ResponseErrorConfig<PostAuthLogin401 | PostAuthLogin422>,
    { data: PostAuthLoginMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postAuthLogin(data, config);
    }
  });
}

/**
 * @summary Sign in with email + password
 * {@link /v1/auth/login}
 */
export function usePostAuthLogin<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAuthLoginMutationResponse,
      ResponseErrorConfig<PostAuthLogin401 | PostAuthLogin422>,
      { data: PostAuthLoginMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostAuthLoginMutationRequest>> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postAuthLoginMutationKey();

  const baseOptions = postAuthLoginMutationOptions(config) as UseMutationOptions<
    PostAuthLoginMutationResponse,
    ResponseErrorConfig<PostAuthLogin401 | PostAuthLogin422>,
    { data: PostAuthLoginMutationRequest },
    TContext
  >;

  return useMutation<
    PostAuthLoginMutationResponse,
    ResponseErrorConfig<PostAuthLogin401 | PostAuthLogin422>,
    { data: PostAuthLoginMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostAuthLoginMutationResponse,
    ResponseErrorConfig<PostAuthLogin401 | PostAuthLogin422>,
    { data: PostAuthLoginMutationRequest },
    TContext
  >;
}
