/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import fetch from '@/services/fetcher';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/services/fetcher';
import type {
  PostAuthLogoutMutationRequest,
  PostAuthLogoutMutationResponse,
  PostAuthLogout401
} from './PostAuthLogout.ts';

export const postAuthLogoutMutationKey = () => [{ url: '/v1/auth/logout' }] as const;

export type PostAuthLogoutMutationKey = ReturnType<typeof postAuthLogoutMutationKey>;

/**
 * @summary Sign out (invalidate refresh token)
 * {@link /v1/auth/logout}
 */
export async function postAuthLogout(
  data?: PostAuthLogoutMutationRequest,
  config: Partial<RequestConfig<PostAuthLogoutMutationRequest>> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAuthLogoutMutationResponse,
    ResponseErrorConfig<PostAuthLogout401>,
    PostAuthLogoutMutationRequest
  >({ method: 'POST', url: `/v1/auth/logout`, data: requestData, ...requestConfig });
  return res.data;
}

export function postAuthLogoutMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostAuthLogoutMutationRequest>> & { client?: Client } = {}
) {
  const mutationKey = postAuthLogoutMutationKey();
  return mutationOptions<
    PostAuthLogoutMutationResponse,
    ResponseErrorConfig<PostAuthLogout401>,
    { data?: PostAuthLogoutMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postAuthLogout(data, config);
    }
  });
}

/**
 * @summary Sign out (invalidate refresh token)
 * {@link /v1/auth/logout}
 */
export function usePostAuthLogout<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAuthLogoutMutationResponse,
      ResponseErrorConfig<PostAuthLogout401>,
      { data?: PostAuthLogoutMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostAuthLogoutMutationRequest>> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postAuthLogoutMutationKey();

  const baseOptions = postAuthLogoutMutationOptions(config) as UseMutationOptions<
    PostAuthLogoutMutationResponse,
    ResponseErrorConfig<PostAuthLogout401>,
    { data?: PostAuthLogoutMutationRequest },
    TContext
  >;

  return useMutation<
    PostAuthLogoutMutationResponse,
    ResponseErrorConfig<PostAuthLogout401>,
    { data?: PostAuthLogoutMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    PostAuthLogoutMutationResponse,
    ResponseErrorConfig<PostAuthLogout401>,
    { data?: PostAuthLogoutMutationRequest },
    TContext
  >;
}
