/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query';
import { mutationOptions, useMutation } from '@tanstack/react-query';
import fetch from '@/services/fetcher';
import type { Client, RequestConfig, ResponseErrorConfig } from '@/services/fetcher';
import type {
  UpdateTodoMutationRequest,
  UpdateTodoMutationResponse,
  UpdateTodoPathParams,
  UpdateTodo401,
  UpdateTodo404,
  UpdateTodo422
} from './UpdateTodo.ts';

export const updateTodoMutationKey = () => [{ url: '/v1/todos/:id' }] as const;

export type UpdateTodoMutationKey = ReturnType<typeof updateTodoMutationKey>;

/**
 * @summary Update todo (partial)
 * {@link /v1/todos/:id}
 */
export async function updateTodo(
  id: UpdateTodoPathParams['id'],
  data: UpdateTodoMutationRequest,
  config: Partial<RequestConfig<UpdateTodoMutationRequest>> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdateTodoMutationResponse,
    ResponseErrorConfig<UpdateTodo401 | UpdateTodo404 | UpdateTodo422>,
    UpdateTodoMutationRequest
  >({ method: 'PUT', url: `/v1/todos/${id}`, data: requestData, ...requestConfig });
  return res.data;
}

export function updateTodoMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<UpdateTodoMutationRequest>> & { client?: Client } = {}
) {
  const mutationKey = updateTodoMutationKey();
  return mutationOptions<
    UpdateTodoMutationResponse,
    ResponseErrorConfig<UpdateTodo401 | UpdateTodo404 | UpdateTodo422>,
    { id: UpdateTodoPathParams['id']; data: UpdateTodoMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return updateTodo(id, data, config);
    }
  });
}

/**
 * @summary Update todo (partial)
 * {@link /v1/todos/:id}
 */
export function useUpdateTodo<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateTodoMutationResponse,
      ResponseErrorConfig<UpdateTodo401 | UpdateTodo404 | UpdateTodo422>,
      { id: UpdateTodoPathParams['id']; data: UpdateTodoMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpdateTodoMutationRequest>> & { client?: Client };
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateTodoMutationKey();

  const baseOptions = updateTodoMutationOptions(config) as UseMutationOptions<
    UpdateTodoMutationResponse,
    ResponseErrorConfig<UpdateTodo401 | UpdateTodo404 | UpdateTodo422>,
    { id: UpdateTodoPathParams['id']; data: UpdateTodoMutationRequest },
    TContext
  >;

  return useMutation<
    UpdateTodoMutationResponse,
    ResponseErrorConfig<UpdateTodo401 | UpdateTodo404 | UpdateTodo422>,
    { id: UpdateTodoPathParams['id']; data: UpdateTodoMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions
    },
    queryClient
  ) as UseMutationResult<
    UpdateTodoMutationResponse,
    ResponseErrorConfig<UpdateTodo401 | UpdateTodo404 | UpdateTodo422>,
    { id: UpdateTodoPathParams['id']; data: UpdateTodoMutationRequest },
    TContext
  >;
}
