/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ErrorResponse = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @description 5-digit numeric error code
   * @type integer
   */
  code: number;
  /**
   * @type string
   */
  message: string;
  /**
   * @type string, date-time
   */
  timestamp: string;
  /**
   * @type object | undefined
   */
  metadata?: {
    [key: string]: unknown;
  };
};
