/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LoginResponse = {
  /**
   * @type string | undefined
   */
  access_token?: string;
  /**
   * @type string | undefined
   */
  refresh_token?: string;
  /**
   * @type integer | undefined
   */
  access_token_expires_in_sec?: number;
  /**
   * @type integer | undefined
   */
  refresh_token_expires_in_sec?: number;
  /**
   * @description ms-since-epoch
   * @type integer | undefined
   */
  issued_at?: number;
  /**
   * @type object | undefined
   */
  user?: {
    /**
     * @type string | undefined, uuid
     */
    id?: string;
    /**
     * @type string | undefined
     */
    name?: string;
    /**
     * @type string | undefined, email
     */
    email?: string;
  };
  /**
   * @type array | undefined
   */
  permissions?: string[];
};
