/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LoginRequest = {
  /**
   * @type string, email
   */
  email: string;
  /**
   * @minLength 8
   * @maxLength 72
   * @type string
   */
  password: string;
};
