/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Pagination = {
  /**
   * @minLength 1
   * @type integer
   */
  page: number;
  /**
   * @minLength 1
   * @type integer
   */
  page_size: number;
  /**
   * @minLength 0
   * @type integer
   */
  total_data: number;
  /**
   * @minLength 0
   * @type integer
   */
  total_page: number;
};
