/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pagination } from './Pagination.ts';

export type PaginatedResponse = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type integer
   */
  code: number;
  /**
   * @type string
   */
  message: string;
  /**
   * @type array
   */
  data: unknown[];
  /**
   * @type object
   */
  pagination: Pagination;
  /**
   * @type string, date-time
   */
  timestamp: string;
};
