/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RenewResponse = {
  /**
   * @type string | undefined
   */
  access_token?: string;
  /**
   * @type integer | undefined
   */
  access_token_expires_in_sec?: number;
  /**
   * @type integer | undefined
   */
  issued_at?: number;
};
