/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SuccessResponse = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type integer
   */
  code: number;
  /**
   * @type string
   */
  message: string;
  /**
   * @type object
   */
  data: object;
  /**
   * @type string, date-time
   */
  timestamp: string;
};
