/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TodoResponse = {
  /**
   * @type string | undefined, uuid
   */
  id?: string;
  /**
   * @type string | undefined
   */
  title?: string;
  /**
   * @type string | undefined
   */
  description?: string;
  /**
   * @type string, date-time
   */
  due_date?: string | null;
  /**
   * @type string | undefined, date-time
   */
  created_at?: string;
  /**
   * @type string | undefined, uuid
   */
  created_by?: string;
  /**
   * @type string | undefined, date-time
   */
  modified_at?: string;
  /**
   * @type string | undefined, uuid
   */
  modified_by?: string;
};
