/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateTodoRequest = {
  /**
   * @minLength 1
   * @maxLength 200
   * @type string | undefined
   */
  title?: string;
  /**
   * @maxLength 2000
   * @type string | undefined
   */
  description?: string;
  /**
   * @type string | undefined, date-time
   */
  due_date?: string;
};
