/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const httpCommonPaginationResponseWrapperSchema = z.object({
  limit: z.optional(z.number().int()),
  page: z.optional(z.number().int()),
  total_item: z.optional(z.number().int()),
  total_page: z.optional(z.number().int())
});
