/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type HttpCommonPaginationResponseWrapper = {
  /**
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @type integer | undefined
   */
  page?: number;
  /**
   * @type integer | undefined
   */
  total_item?: number;
  /**
   * @type integer | undefined
   */
  total_page?: number;
};
