/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const errorResponseSchema = z.object({
  success: z.boolean(),
  code: z.number().int().describe('5-digit numeric error code'),
  message: z.string(),
  timestamp: z.string().datetime(),
  metadata: z.optional(z.object({}).catchall(z.any()))
});
