/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const loginRequestSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8).max(72)
});
