/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const loginResponseSchema = z.object({
  access_token: z.optional(z.string()),
  refresh_token: z.optional(z.string()),
  access_token_expires_in_sec: z.optional(z.number().int()),
  refresh_token_expires_in_sec: z.optional(z.number().int()),
  issued_at: z.optional(z.number().int().describe('ms-since-epoch')),
  user: z.optional(
    z.object({
      id: z.optional(z.string().uuid()),
      name: z.optional(z.string()),
      email: z.optional(z.string().email())
    })
  ),
  permissions: z.optional(z.array(z.string()))
});
