/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';
import { paginationSchema } from './paginationSchema.ts';

export const paginatedResponseSchema = z.object({
  success: z.boolean(),
  code: z.number().int(),
  message: z.string(),
  data: z.array(z.any()),
  pagination: z.lazy(() => paginationSchema),
  timestamp: z.string().datetime()
});
