/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const paginationSchema = z.object({
  page: z.number().int().min(1),
  page_size: z.number().int().min(1),
  total_data: z.number().int().min(0),
  total_page: z.number().int().min(0)
});
