/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const renewResponseSchema = z.object({
  access_token: z.optional(z.string()),
  access_token_expires_in_sec: z.optional(z.number().int()),
  issued_at: z.optional(z.number().int())
});
