/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const successResponseSchema = z.object({
  success: z.boolean(),
  code: z.number().int(),
  message: z.string(),
  data: z.object({}),
  timestamp: z.string().datetime()
});
