/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const todoResponseSchema = z.object({
  id: z.optional(z.string().uuid()),
  title: z.optional(z.string()),
  description: z.optional(z.string()),
  due_date: z.string().datetime().nullish(),
  created_at: z.optional(z.string().datetime()),
  created_by: z.optional(z.string().uuid()),
  modified_at: z.optional(z.string().datetime()),
  modified_by: z.optional(z.string().uuid())
});
