/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod';

export const updateTodoRequestSchema = z.object({
  title: z.optional(z.string().min(1).max(200)),
  description: z.optional(z.string().max(2000)),
  due_date: z.optional(z.string().datetime())
});
